### ISSUE TITLE
Cloudbase-init Account

### ISSUE THREAD

**Issue by T0schi** [cloudbase/windows-openstack-imaging-tools#330] opened 2019-12-10 06:35 UTC
Hello,
After the update of the imaging tools (downloaded end of October) i found a change in the properties of the Cloudbase-init Service. In deployed Win Server OS the Cloudbase-init Service has changed from a specific account to Local System account. 

Before
![image](https://user-images.githubusercontent.com/56817514/70501223-c5843980-1b1d-11ea-8434-b446d5a83cab.png)

After
![image](https://user-images.githubusercontent.com/56817514/70501249-d3d25580-1b1d-11ea-9a6b-4340fa4043c0.png)

I have found an entry [here](https://github.com/cloudbase/cloudbase-init-installer/blob/b2fbc293a4b62fb02c835c9a1a9065afe36dc37c/CloudbaseInitSetup/Dialogs/ConfigDlg.wxs#L33), but i haven´t found the place were i can switch this value. We have a usecase from developer side for the Cloudbase-init user.

Was this change performed within the automatic download of the installer during the image creation or where can i switch back to the specific account?
![image](https://user-images.githubusercontent.com/56817514/70501728-25c7ab00-1b1f-11ea-9ad0-73b04bcb8e51.png)

Thank you for your help.

**Comment by ader1990** [comment] 2019-12-10 11:30
Hello @T0schi,

The behaviour should not have changed between patches, so I think it is a imaging tools config issue.
Make sure that the configuration file has the cloudbase_init_use_local_system set to False or it does not have it at all. The default behaviour is to create a special user named cloudbase-init and use it:

```bash
[cloudbase_init]
cloudbase_init_use_local_system=False
```

This is the config entry definition:
https://github.com/cloudbase/windows-openstack-imaging-tools/blob/master/Config.psm1#L150

Let me know if this was the case for you.

Thank you,
Adrian Vladu

**Comment by T0schi** [comment] 2019-12-10 12:09
Hello @ader1990 
that are mine outputs from 
Config File of the image (Server 2019 e.g)
![image](https://user-images.githubusercontent.com/56817514/70528197-eb293700-1b4d-11ea-9e4a-f30855083f89.png)

and Config.psm1
`@{"Name" = "cloudbase_init_use_local_system"; "GroupName" = "cloudbase_init"; "AsBoolean" = $true; "DefaultValue" = $false;
          "Description" = "If set, the Cloudbase-Init service will be run under Local System account.
                           By default, a user named cloudbase-init with admin rights is created and used."},`

I did no changes on this parts.

**Comment by ader1990** [comment] 2019-12-10 12:23
I understand, can you share the config file that you use so that I can try to reproduce the issue?

**Comment by T0schi** [comment] 2019-12-10 12:31
Here it is

[2019stdV_Q4.zip](https://github.com/cloudbase/windows-openstack-imaging-tools/files/3944824/2019stdV_Q4.zip)

**Comment by ader1990** [comment] 2019-12-18 14:58
@T0schi I found the issue and there is a regression on a previous feature, that is fixed by pull request https://github.com/cloudbase/windows-openstack-imaging-tools/pull/333.  Can you verify that the issue is fixed by the PR?

Thank you,
Adrian Vladu

**Comment by T0schi** [comment] 2019-12-19 06:41
Thank you for the reply,
i will test it next week and let you know the result.

**Closed** 2019-12-19 13:57 UTC

**Comment by ader1990** [comment] 2020-01-20 15:22
@T0schi, thank you for the feedback.
