### ISSUE TITLE
Windows 7 image always restarting

### ISSUE THREAD

**Issue by yasmindemiral** [cloudbase/windows-openstack-imaging-tools#207] opened 2018-06-25 14:56 UTC
I created windows 7 qcow2 image, i uploaded openstack and created instance. But the instance always restart again again. How can i do it ?

**Comment by ader1990** [comment] 2018-06-25 15:08
Hello,

Please consult: https://github.com/cloudbase/windows-openstack-imaging-tools#i-booted-an-instance-with-the-image-and-i-got-a-bsod

Thanks.

**Comment by yasmindemiral** [comment] 2018-06-25 15:31
the below code is driver part of conf.ini file . I dont understand, what is the virtio_iso_path ? And how can i flag enable kvm flag ? Where ?

[drivers]
# The path to the ISO file containing the VirtIO drivers.
virtio_iso_path=""
# The location where the VirtIO drivers are found.
# For example, the location of a mounted VirtIO ISO. VirtIO versions supported >=0.1.6.x
# The location where the VirtIO drivers are found.
# For example, the location of a mounted VirtIO ISO. VirtIO versions supported >=0.1.6.x
virtio_base_path="C:\Users\Administrator\Downloads\virtio-win-0.1.133.iso"
# The location where additional drivers that are needed for the image are located.
drivers_path=""

**Comment by ader1990** [comment] 2018-06-25 16:03
Hello,

If you already have the virtio ISO at this path: "C:\Users\Administrator\Downloads\virtio-win-0.1.133.iso", the windows image generation config should be:
[drivers]
virtio_iso_path="C:\Users\Administrator\Downloads\virtio-win-0.1.133.iso"
virtio_base_path=""
drivers_path=""

On the hypervisor part, the nova-compute servers (assuming you are using libvirt-kvm), should be configured to use kvm virtualization. Make sure that in the nova-compute configuration you have:
[libvirt]
virt_type = kvm

Thank you,
Adrian Vladu

**Comment by ader1990** [comment] 2018-06-25 16:11
Bellow you can find more information on the options for the drivers' configuration:

[drivers]
# The path to the ISO file containing the VirtIO drivers."
virtio_iso_path="C:\Users\Administrator\Downloads\virtio-win-0.1.133.iso"
# The location where the VirtIO drivers are found.
# For example, the location of a mounted VirtIO ISO. VirtIO versions supported >=0.1.6.x
virtio_base_path=""
# The location where additional drivers that are needed for the image are located.
drivers_path=""

**Comment by yasmindemiral** [comment] 2018-06-26 05:48
I checked openstack configuration and kvm is enable, but the windows instance is same this picture [1]
[1] https://pasteboard.co/HrDt4DG.png
when i writo virtio path to virtio_iso_path section, it didnt work, virtı_base_path working. But i cant run on openstack

**Comment by ader1990** [comment] 2018-06-26 09:21
Hello,

Can you give more information on what didn't work if you set: "virtio path to virtio_iso_path section"? The windows image generation logs would be great.
Setting the virtio ISO path is a requirement ot have the virtio drivers installed.

Thanks.

**Comment by ader1990** [comment] 2018-06-26 09:50
You can also make sure the OpenStack environment  is okay by testing it with a Windows 2012 R2 kvm evaluation image prepared for OpenStack kvm.

Here is the download link: https://cloudbase.it/windows-cloud-images/#download

**Comment by yasmindemiral** [comment] 2018-06-26 10:21
Yeah, i can run Windows 2012 R2 kvm  image, it is worked. 
Where is the logs about windows image generation ?

**Comment by yasmindemiral** [comment] 2018-06-26 12:05
I see this error : The Open vSwitch Service service terminated unexpectedly.  It has done this 1 time(s).  The following corrective action will be taken in 0 milliseconds: Restart the service.

Is it important ? I dont any idea.

**Comment by ader1990** [comment] 2018-06-26 13:32
On what version of Windows are you trying to generate the image?
This seems to be an error with mounting ISO files.

You can try to manually mount the ISO file and set the mount point location:
```[drivers]
# The path to the ISO file containing the VirtIO drivers."
virtio_iso_path=""
# The location where the VirtIO drivers are found.
# For example, the location of a mounted VirtIO ISO. VirtIO versions supported >=0.1.6.x
virtio_base_path="<path where the virtio iso is mounted"
```

**Comment by yasmindemiral** [comment] 2018-06-27 05:08
I work on Windows Server 2016. I try to mount on powershell, it has still appling image for yesterday

**Comment by yasmindemiral** [comment] 2018-06-27 05:56
It gave same error, 
PS C:\Users\Administrator\windows-openstack-imaging-tools> Mount-DiskImage -ImagePath C:\Users\Administrator\Downloads\Win8.1_English_
x64.iso
PS C:\Users\Administrator\windows-openstack-imaging-tools> New-WindowsOnlineImage -ConfigFilePath $ConfigFilePath
26.06.2018 16:55:27 - Windows online image generation started.
26.06.2018 16:55:32 - Cloud image generation started.
26.06.2018 16:55:34 - Creating Virtual Disk Image: C:\Users\ADMINI~1\win8.vhdx...
26.06.2018 16:55:37 - Successfuly created disk: C:\Users\ADMINI~1\win8.vhdx
26.06.2018 16:55:37 - Generate Unattend Xml :F:\Unattend.xml...
26.06.2018 16:55:37 - Xml was generated.
26.06.2018 16:55:37 - Copy Unattend Resources: Client...
26.06.2018 16:55:37 - Copying: C:\Users\Administrator\windows-openstack-imaging-tools\UnattendResources F:\UnattendResources
26.06.2018 16:55:37 - Resources have been copied.
26.06.2018 16:55:37 - Copy Custom Resources: ...
26.06.2018 16:55:37 - Custom Resources at: F:\UnattendResources.
26.06.2018 16:55:37 - Set Wallpaper: ...
26.06.2018 16:55:37 - Wallpaper copied to the image.
26.06.2018 16:55:37 - Wallpaper GPO copied to the image.
26.06.2018 16:55:37 - Wallpaper was set.
26.06.2018 16:55:37 - Downloading Cloudbase-Init...
26.06.2018 16:55:42 - Applying Windows image "E:\sources\install.wim" in "F:\"

Deployment Image Servicing and Management tool
Version: 10.0.14393.0

Applying image
[==========================100.0%==========================]
The operation completed successfully.
27.06.2018 08:25:38 - Create BCDBoot Config: WIMInterop.WimImage.ImageName...
The operation completed successfully.
The operation completed successfully.
The operation completed successfully.
27.06.2018 08:25:38 - BCDBoot config has been created.
27.06.2018 08:25:38 - Adding Virtual IO Drivers from ISO: C:\Users\Administrator\Downloads\virtio-win-0.1.141.iso...
27.06.2018 08:25:43 - Exception calling "OpenVirtualDisk" with "1" argument(s): "Unrecognized file format: İSO"
Add-VirtIODriversFromISO : Exception calling "OpenVirtualDisk" with "1" argument(s): "Unrecognized file format: İSO"
At C:\Users\Administrator\windows-openstack-imaging-tools\WinImageBuilder.psm1:1325 char:13
+             Add-VirtIODriversFromISO $winImagePath $image $windowsIma ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-VirtIODriversFromISO], MethodInvocationException
    + FullyQualifiedErrorId : Exception,Add-VirtIODriversFromISO

PS C:\Users\Administrator\windows-openstack-imaging-tools>

**Comment by ader1990** [comment] 2018-06-27 12:36
Can you try generate the image after you remove the line: virtio_iso_path="" and leave only virtio_base_path="<path where the virtio iso is mounted" from the section drivers in the config file?

Thanks.

**Comment by yasmindemiral** [comment] 2018-06-27 13:47
Yes, when i use virtio_base_path section, image created successfully. But the windows restart always and gives blue screen. How can watch logs or something, how can i detect problem ?

**Comment by yasmindemiral** [comment] 2018-07-05 11:32
I run create-windows-online-cloud-image.ps1 but it gave same error. İSO file format Unrecognized, is there any bug in source code. it is İSO not ISO ?  

[==========================100.0%==========================] 
The operation completed successfully.
5.07.2018 13:57:13 - Create BCDBoot Config: WIMInterop.WimImage.ImageName...
The operation completed successfully.
The operation completed successfully.
The operation completed successfully.
5.07.2018 13:57:18 - BCDBoot config has been created.
5.07.2018 13:57:18 - Adding Virtual IO Drivers from ISO: C:\Users\Administrator\virtio.iso...
5.07.2018 13:57:25 - Exception calling "OpenVirtualDisk" with "1" argument(s): "Unrecognized file format: İSO"
Add-VirtIODriversFromISO : Exception calling "OpenVirtualDisk" with "1" argument(s): "Unrecognized file format: İSO"
At C:\Users\Administrator\windows-openstack-imaging-tools\WinImageBuilder.psm1:1325 char:13
+             Add-VirtIODriversFromISO $winImagePath $image $windowsIma ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-VirtIODriversFromISO], MethodInvocationException
    + FullyQualifiedErrorId : Exception,Add-VirtIODriversFromISO

**Comment by ader1990** [comment] 2018-07-05 11:43
can you paste here from the OpenStack KVM node where that Windows instance runs the output of this command?

```bash
ps auxf | grep qemu
```

**Comment by yasmindemiral** [comment] 2018-07-05 11:50
result is : http://paste.openstack.org/show/725109/

**Comment by yasmindemiral** [comment] 2018-07-05 11:51
windows instance is : http://paste.openstack.org/show/725111/

**Comment by ader1990** [comment] 2018-07-05 12:02
If the virtio drivers were successfully installed and kvm is enabled, the only issue I can think of is that the KVM does not expose the required CPU flags for Windows to run (https://ask.cloudbase.it/question/1227/nano-server-wont-boot/)

Can you send the full logs for the image generation (the ones from the PowerShell console), to check if the virtio drivers were properly applied?

One more thing you can try is to set in the nova.conf on the compute node:
```ini
  [libvirt]
  cpu_mode=host-passthrough
```

Thanks,
Adrian Vladu

**Comment by yasmindemiral** [comment] 2018-07-05 12:08
the powershell full log is http://paste.openstack.org/show/725114/

How can i check virtio driver is appied or not ? the cloudbase windows 2012 image is working our openstack system, but i cant instances with new created windows image

**Comment by ader1990** [comment] 2018-07-05 12:17
It does not find any virtio drivers here:

5.07.2018 12:07:24 - Adding Virtual IO Drivers: F:\virtio-win-0.1.1...
5.07.2018 12:07:24 - Getting Virtual IO Drivers: F:\virtio-win-0.1.1...
5.07.2018 12:07:24 - Getting Virtual IO Drivers: F:\virtio-win-0.1.1...
5.07.2018 12:07:24 - Virtual IO Drivers was added.

Make sure that virtio_base_path = "F:"

**Comment by yasmindemiral** [comment] 2018-07-05 12:22
I mounted virtio.iso file to F:\ . Is it wrong ?

**Comment by ader1990** [comment] 2018-07-05 13:09
Is not wrong that you mounted the ISO on F:\, but it is wrong that you have set the virtio drivers path to "F:\virtio-win-0.1.1", it should be the mount point, which is F:\

**Comment by yasmindemiral** [comment] 2018-07-06 08:12
I can run windows server 2016, but i cant run windows 10, it does not have install.wim, i use boot.wim and name is  Microsoft Windows PE (x64) , but not working. 
Also i run 8.1, its screen is inverse like mirror, but i can fix it ?

**Comment by yasmindemiral** [comment] 2018-07-06 12:14
I try to run Windows 7, but windows-imaging-tools gave an error : http://paste.openstack.org/show/725241/

**Comment by yasmindemiral** [comment] 2018-07-09 07:46
I dont solve Windows 7 and Windows 10 problems, do you help me ?

**Comment by ader1990** [comment] 2018-07-09 11:46
Hello,

answers inline >>

>> "but i cant run windows 10, it does not have install.wim, i use boot.wim and name is Microsoft Windows PE (x64) , but not working." - this seems like an ISO problem, an iso should always have the install.wim file.

>> "Also i run 8.1, its screen is inverse like mirror, I am using spice console how can i fix it ?" - This seems an OpenStack issue, I do not have any information on that issue.

>> "I try to run Windows 7, but windows-imaging-tools gave an error http://paste.openstack.org/show/725241/" - this looks like an uefi/bcd store problem, but I need some more details on the ISO files you are using.

What ISO versions(ISO full name) are you using when trying to generate the corresponding images for Win 10 and Win7?
I will try to reproduce the issue you've got. Also, make sure you have a clean environment for the image generation (fresh host OS install, latest patches, even a reboot might help sometimes).

Thanks,
Adrian.

**Comment by ader1990** [comment] 2018-07-10 14:42
Closing this issue, as the initial problem has been solved.
The problem with the Win7 image generation will be tracked on issue #216 page

**Closed by ader1990** 2018-07-10 14:42 UTC
Labels: question
