### ISSUE TITLE
Server 2008 R2 generation fails with bcdedit error

### ISSUE THREAD

**Issue by tomcsanyid** [cloudbase/windows-openstack-imaging-tools#53] opened 2016-03-11 12:28 UTC
Server 2008 R2 has an older version of bcdedit which fails on the three instructions starting here:
https://github.com/cloudbase/windows-openstack-imaging-tools/blob/master/WinImageBuilder.psm1#L149

It doesn't contain the "locate" device. Changing it to "boot" seems to be an easy fix. 
**Proposed solution:** using the logic just above it that determines the parameters for bcdboot.exe to determine the parameters for bcdedit as well.

Exact error message:

```
The device is not valid as specified.
Run "bcdedit /?" for command line assistance.
The parameter is incorrect.
```

**Comment by Parth6288** [comment] 2016-09-08 07:09
Hi, I am also facing the same issue. Can you please provide the exact code that you used to fix the same.

**Comment by tomcsanyid** [comment] 2016-09-08 14:06
@Parth6288 sure, here it is:

        & $bcdeditPath /store ${systemDrive}\boot\BCD /set `{bootmgr`} device boot
        if($LASTEXITCODE) { throw "BCDEdit failed: device boot1" }

        & $bcdeditPath /store ${systemDrive}\boot\BCD /set `{default`} device boot
        if($LASTEXITCODE) { throw "BCDEdit failed: device boot2" }

        & $bcdeditPath /store ${systemDrive}\boot\BCD /set `{default`} osdevice boot
        if($LASTEXITCODE) { throw "BCDEdit failed: osdevice boot" }

Notice the "boot" parameter at the end instead of "locate".

**Comment by Parth6288** [comment] 2016-09-09 04:37
Thanks, Tom. I was able to get it working. However I am stuck with another issue. Using the -installupdate parameter the instance checks the WSUS server for available updates and accepts it. however it gets stuck at the downloading phase and proceeds with next part of the script which is to install cloudbase init. Please find attached screenshot of the same.

![error](https://cloud.githubusercontent.com/assets/16204776/18375577/30d1c082-7675-11e6-92aa-532a7b941289.JPG)

**Comment by Parth6288** [comment] 2016-09-09 04:41
Below is the Windowsupdate logs.
** START **  Agent: Finding updates [CallerId = AutomaticUpdates]
2016-09-08	10:48:19:500	 848	604	Agent	*********
2016-09-08	10:48:19:500	 848	604	Agent	  * Online = Yes; Ignore download priority = No
2016-09-08	10:48:19:500	 848	604	Agent	  * Criteria = "IsInstalled=0 and DeploymentAction='Installation' or IsPresent=1 and DeploymentAction='Uninstallation' or IsInstalled=1 and DeploymentAction='Installation' and RebootRequired=1 or IsInstalled=0 and DeploymentAction='Uninstallation' and RebootRequired=1"
2016-09-08	10:48:19:500	 848	604	Agent	  * ServiceID = {3DA21691-E39D-4DA6-8A4B-B43877BCB1B7} Managed
2016-09-08	10:48:19:500	 848	604	Agent	  * Search Scope = {Machine}
2016-09-08	10:48:19:515	 848	604	Setup	Checking for agent SelfUpdate
2016-09-08	10:48:19:515	 848	604	Setup	Client version: Core: 7.6.7600.256  Aux: 7.3.7600.16385
2016-09-08	10:48:43:109	 848	604	Misc	WARNING: Send failed with hr = 80072ee2.
2016-09-08	10:48:43:109	 848	604	Misc	WARNING: SendRequest failed with hr = 80072ee2. Proxy List used: <(null)> Bypass List used : <(null)> Auth Schemes used : <>
2016-09-08	10:48:43:109	 848	604	Misc	WARNING: WinHttp: SendRequestUsingProxy failed for <http://mywsusurl//selfupdate/wuident.cab>. error 0x80072ee2
2016-09-08	10:48:43:109	 848	604	Misc	WARNING: WinHttp: SendRequestToServerForFileInformation MakeRequest failed. error 0x80072ee2
2016-09-08	10:48:43:109	 848	604	Misc	WARNING: WinHttp: SendRequestToServerForFileInformation failed with 0x80072ee2
2016-09-08	10:48:43:109	 848	604	Misc	WARNING: WinHttp: ShouldFileBeDownloaded failed with 0x80072ee2
2016-09-08	10:49:06:703	 848	604	Misc	WARNING: Send failed with hr = 80072ee2.
2016-09-08	10:49:06:703	 848	604	Misc	WARNING: SendRequest failed with hr = 80072ee2. Proxy List used: <(null)> Bypass List used : <(null)> Auth Schemes used : <>
2016-09-08	10:49:06:703	 848	604	Misc	WARNING: WinHttp: SendRequestUsingProxy failed for <http://mywsusurl//selfupdate/wuident.cab>. error 0x80072ee2
2016-09-08	10:49:06:703	 848	604	Misc	WARNING: WinHttp: SendRequestToServerForFileInformation MakeRequest failed. error 0x80072ee2
2016-09-08	10:49:06:703	 848	604	Misc	WARNING: WinHttp: SendRequestToServerForFileInformation failed with 0x80072ee2
2016-09-08	10:49:06:703	 848	604	Misc	WARNING: WinHttp: ShouldFileBeDownloaded failed with 0x80072ee2
2016-09-08	10:49:30:281	 848	604	Misc	WARNING: Send failed with hr = 80072ee2.
2016-09-08	10:49:30:281	 848	604	Misc	WARNING: SendRequest failed with hr = 80072ee2. Proxy List used: <(null)> Bypass List used : <(null)> Auth Schemes used : <>
2016-09-08	10:49:30:281	 848	604	Misc	WARNING: WinHttp: SendRequestUsingProxy failed for <http://mywsusurl//selfupdate/wuident.cab>. error 0x80072ee2
2016-09-08	10:49:30:281	 848	604	Misc	WARNING: WinHttp: SendRequestToServerForFileInformation MakeRequest failed. error 0x80072ee2
2016-09-08	10:49:30:281	 848	604	Misc	WARNING: WinHttp: SendRequestToServerForFileInformation failed with 0x80072ee2
2016-09-08	10:49:30:281	 848	604	Misc	WARNING: WinHttp: ShouldFileBeDownloaded failed with 0x80072ee2
2016-09-08	10:49:53:859	 848	604	Misc	WARNING: Send failed with hr = 80072ee2.
2016-09-08	10:49:53:859	 848	604	Misc	WARNING: SendRequest failed with hr = 80072ee2. Proxy List used: <(null)> Bypass List used : <(null)> Auth Schemes used : <>
2016-09-08	10:49:53:859	 848	604	Misc	WARNING: WinHttp: SendRequestUsingProxy failed for <http://mywsusurl//selfupdate/wuident.cab>. error 0x80072ee2
2016-09-08	10:49:53:859	 848	604	Misc	WARNING: WinHttp: SendRequestToServerForFileInformation MakeRequest failed. error 0x80072ee2
2016-09-08	10:49:53:859	 848	604	Misc	WARNING: WinHttp: SendRequestToServerForFileInformation failed with 0x80072ee2
2016-09-08	10:49:53:859	 848	604	Misc	WARNING: WinHttp: ShouldFileBeDownloaded failed with 0x80072ee2
2016-09-08	10:49:53:859	 848	604	Misc	WARNING: DownloadFileInternal failed for http://mywsusurl//selfupdate/wuident.cab: error 0x80072ee2
2016-09-08	10:49:53:859	 848	604	Setup	WARNING: SelfUpdate check failed to download package information, error = 0x80072EE2
2016-09-08	10:49:53:859	 848	604	Setup	FATAL: SelfUpdate check failed, err = 0x80072EE2
2016-09-08	10:49:53:859	 848	604	Agent	  * WARNING: Skipping scan, self-update check returned 0x80072EE2
2016-09-08	10:49:53:859	 848	604	Agent	  * WARNING: Exit code = 0x80072EE2
2016-09-08	10:49:53:859	 848	604	Agent	*********
2016-09-08	10:49:53:859	 848	604	Agent	**  END  **  Agent: Finding updates [CallerId = AutomaticUpdates]
2016-09-08	10:49:53:859	 848	604	Agent	*************
2016-09-08	10:49:53:859	 848	604	Agent	WARNING: WU client failed Searching for update with error 0x80072ee2

**Comment by ader1990** [comment] 2016-09-09 08:59
Hello Parth,

I have seen contradictory information on your issues with the updates being installed, as you stated here: http://ask.cloudbase.it/question/1428/unable-to-download-and-install-windows-patch-in-windows-2012-std/ that on 2008r2 the updates were installed correctly, but you are stating above that also 2008r2 updates' installation fails.

Can you restate on what versions of Windows do you encounter this issue?

Moreover, can you give some information on how your WSUS has been configured, in order to try to reproduce your setup?

The imaging scripts have not been tested with WSUS (although if WSUS server has been set correctly, it should be transparent for the scripts) and this requires more investigation from our part.

We should also move this conversation to another Github issues, as it does not apply to the issue described in the title.

Thank you,
Adrian Vladu

**Comment by Parth6288** [comment] 2016-09-09 11:33
Hi Adrian,
I have created a new Github issue for this and provided complete details on the issue. 
Thanks,
Parth

**Comment by ader1990** [comment] 2018-06-27 13:30
closing issue, as it is more than one year old and the issue is no longer present.

**Closed by ader1990** 2018-06-27 13:30 UTC
