### ISSUE TITLE
driversBasePath is missing?

### ISSUE THREAD

**Issue by Brardith** [cloudbase/windows-openstack-imaging-tools#270] opened 2019-06-12 19:30 UTC
Attempting to build with a modified create-windows-online-cloud-images.ps1, this is my error output:

Edit: I am running out of master branch, cloned on June 12 2019

```6/12/2019 12:22:15 PM - A parameter cannot be found that matches parameter name 'driversBasePath'.
New-WindowsCloudImage : A parameter cannot be found that matches parameter name 'driversBasePath'.
At C:\Users\brardith\Documents\windows-openstack-imaging-tools\WinImageBuilder.psm1:1222 char:9
+         New-WindowsCloudImage -ConfigFilePath $offlineConfigFilePath
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-WindowsCloudImage], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-WindowsCloudImage
```

**Comment by ilenghel** [comment] 2019-06-13 07:51
Hello,

I am guessing you want to add VirtIO drivers to you image. This can be achieved in two ways:
1. Using virtio_iso_path parameter, and giving it the path to a local ISO of the VirtIO drivers.
2. Using virtio_base_path, and giving it the path to a directory that contains the VirtIO drivers. In this case the directory can be the drive letter of a mounted ISO.

The New-WindowsOnlineImage function will detect if you specified one or the other and will use the appropriate method of adding the drivers to your image.

If this doesn't help, please share your modified create-windows-online-cloud-images.ps1 and we can debug it further from there.

**Comment by ilenghel** [comment] 2019-06-13 13:00
Seems like this was caused by an incorrect parameter name on our side.
Please use the latest code  and it should work now.

Thank you for reporting this.

**Comment by ader1990** [comment] 2019-06-14 09:42
Fix merged, @Brardith can you check if it works now in your setup? Thank you.

**Comment by Brardith** [comment] 2019-06-14 18:18
@ader1990 I grabbed the code from the PR yesterday and got it to work offline. Online I've got something wrong with my external vswitch, but that's all my fault! I think it's safe to say this specific issue is resolved.

**Comment by ader1990** [comment] 2019-07-03 14:26
@Brardith glad it all worked out!

**Closed** 2019-07-03 14:25 UTC
